### PR TITLE
Adding new extraction function for FETs-CV, Adding new regression fo MOS-CV

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Adding new extraction function for FETs-CV, Adding new regression for MOS-CV, Rearranging all scripts and cleaning some dirs.

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Is the CI ready to run for models? Could you please enable it before merge?

**Comment by FaragElsayed2** [comment]
@atorkmabrains I have disable it untill we are done with all devices as It will need some changes due to new regressions and so on.

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Pull request merged**
