### PR TITLE
Updating Pcells testing to use PV repo for GF180MCU

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Updating Pcells testing to use PV repo for GF180MCU

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Makefile used for testing has been updated. 

`generate_pcell.py` script used for testcases generation doesn't work. I have opened an issue for that. #125

**Comment by atorkmabrains** [comment]
@FaragElsayed2 What's the status?

**Comment by FaragElsayed2** [comment]
@atorkmabrains As I mentioned, the DRC testing setup is ready but the Pcells generator itself doesn't work.

**Comment by atorkmabrains** [comment]
Thanks @FaragElsayed2 Appreciate the change.

**Comment by FaragElsayed2** [comment]
@atorkmabrains Could you please merge this as I need to use it in Pcells testing ?

**Pull request merged**
