### PR TITLE
Fixing diode pcells drc issues

### PR DESCRIPTION
**Pull request by RehabSayed-G**
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by RehabSayed-G** [comment]
drc testing results for pcells patterns : 
* diode_nd2ps : 
image

* diode_pd2nw : 
image

* diode_nw2ps : 
image

* diode_pw2dw : 
image

* diode_dw2ps : 
image

* sc_diode : 
image

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , ready for testing and review

**Review by FaragElsayed2 — APPROVED** [review]

**Comment by FaragElsayed2** [comment]
@RehabSayed-G Please solve conflict

**Comment by RehabSayed-G** [comment]
> @RehabSayed-G Please solve conflict

@FaragElsayed2 , Done

**Pull request merged**
