### PR TITLE
fixing start amd end layers names

### PR DESCRIPTION
**Pull request by RehabSayed-G**
fixing start and end layers naming

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , ready for review

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , all drc violations are now fixed : 
tested over the shown patterns 
image

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , please review

**Comment by FaragElsayed2** [comment]
@RehabSayed-G Please fix linting issues

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , please review

**Review by FaragElsayed2 — APPROVED** [review]

**Pull request merged**
