### PR TITLE
Cleaning and fixing some issues in xyce regression for GF180MCU

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Cleaning and fixing some issues in xyce regression for GF180MCU

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Does that complete the Xyce regression updates?

**Comment by FaragElsayed2** [comment]
@atorkmabrains No but it's some old fixes

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Pull request merged**
