### PR TITLE
Extracting diode_iv data and adding new regression for it for ngspice models

### PR DESCRIPTION
**Pull request by FaragElsayed2**

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Comment by FaragElsayed2** [comment]
@atorkmabrains Solved

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Pull request merged**
