### PR TITLE
fet pcells lvs testing 

### PR DESCRIPTION
**Pull request by RehabSayed-G**
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by RehabSayed-G** [comment]
lvs testing results for pcells patterns : 
- nfet_03v3_pcells : 
image

- nfet_03v3_dn_pcells : 
image

- nfet_05v0_pcells : 
image


- nfet_05v0_dn_pcells : 
image

- nfet_06v0_pcells : 
image

- nfet_06v0_dn_pcells : 
image

- nfet_06v0_nvt_pcells : 
image

- pfet_03v3_pcells : 
image

- pfet_03v3_dn_pcells : 
image

- pfet_05v0_pcells :
image

- pfet_05v0_dn_pcells : 
image

- pfet_06v0_pcells : 
image

- pfet_06v0_dn_pcells : 
image

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , ready for testing and review

**Comment by FaragElsayed2** [comment]
@RehabSayed-G Why CI still fails ?

**Comment by RehabSayed-G** [comment]
> @RehabSayed-G Why CI still fails ?

CI fails in pcell_regression due to paths error (the testing scripts it self need to be re-implemented as it was written before lvs and drc transferred to pv repo)

**Comment by FaragElsayed2** [comment]
@RehabSayed-G I have updated `Makefile` used for DRC testing to use PV repo. Check it and verify it works well.

We have to do that also for LVS, ignore testing using pytest for now.

**Comment by FaragElsayed2** [comment]
@RehabSayed-G I will merge this one, please add separate PR for CI

**Pull request merged**
