### PR TITLE
fixing mim_cap drc issues and adding its patterns

### PR DESCRIPTION
**Pull request by RehabSayed-G**
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by RehabSayed-G** [comment]
drc testing results for pcells patterns :
* mim_A :
variant_E :
image

* mim_B_4LM : 
variant B : 
image

* mim_B_5LM : 
variant C :
image

* mim_B_6LM :
variant D : 
image

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , ready for testing and review

**Review by FaragElsayed2 — APPROVED** [review]

**Comment by FaragElsayed2** [comment]
@RehabSayed-G Please solve conflict

**Comment by RehabSayed-G** [comment]
> @RehabSayed-G Please solve conflict

Done

**Comment by FaragElsayed2** [comment]
@RehabSayed-G Could you please fix lint and CI issues ?

I will merge other PRs and keep this one for that fix

**Pull request merged**
