### PR TITLE
Adding klayout DRC for GF180MCU from pv repo

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Adding klayout DRC for GF180MCU from pv repo

- Fixing: #122

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Comment by atorkmabrains** [comment]
@FaragElsayed2 As discussed, please remove the sub module from here.

**Comment by FaragElsayed2** [comment]
@atorkmabrains Done

**Comment by FaragElsayed2** [comment]
Could you please merge ? @atorkmabrains

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Pull request merged**
